### PR TITLE
Allow Symfony 6

### LINKED ISSUE #15: Support for Symfony 6
Would you agree to support Symfony 6 since it's been officially out ?

Best regards

### PR DESCRIPTION
**Pull request by vasilvestre**
I had to update CI for Symfony 5.2 => 5.4 and add Sf 6.0 tests ; also I had to fix deprecations by using @return (instead of adding return type to avoid breaking BC)

Fix #15

### CODE REVIEW

**Comment by vasilvestre** [comment]
> Thank you for taking the initiative with this.
> 
> Any change you can remove support for not supported versions ?
> 
> We should really only support PHP 7.4, 8.0, and 8.1. And only LTS versions of Symfony and Symfony 6.0 as well

It may be done by now, could you please approve the Github workflow ?

**Comment by dragosprotung** [comment]
> Edit : 8.1 version require some fixes in dependencies.

I think it's just because of Twig 1 support. I think we can drop this as well

**Comment by dragosprotung** [comment]
Seems to not be the case. Do you want to see if we can fix the deprecations ? I would merge this PR as is as well and later fix the deprecations.

**Comment by vasilvestre** [comment]
> Seems to not be the case. Do you want to see if we can fix the deprecations ? I would merge this PR as is as well and later fix the deprecations.

As you wish. I think we should run tests locally to get more information to trace where the deprecation come from.

**Comment by dragosprotung** [comment]
I will clean up the build process and also upgrade to the new version of the SDK as well and then tag a new release.
Thank you @vasilvestre

**Pull request merged**
